# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_lasmerge_neighbors <- function(las, las_from, k, func, var) {
    .Call('_lasRANN_C_lasmerge_neighbors', PACKAGE = 'lasRANN', las, las_from, k, func, var)
}

C_lasmerge_neighbors_Rfunc <- function(las, las_from, k, func, var) {
    .Call('_lasRANN_C_lasmerge_neighbors_Rfunc', PACKAGE = 'lasRANN', las, las_from, k, func, var)
}

